#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 71c976ed-5ef1-475a-a5c7-a288af2929d6
# Source File: ADUserResetPassword.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
/AEAAB+LCAAAAAAABACNkUFPgzAYhu9L9h8I945BZIyka6IhmB3UhU2v5hM+XLWjpC1b9u+tUham
F2992rfPm6+lBZbyiOqcgQE2nXge3Sj5gaX5AYsvqDSXDYtmcxoM4M5yLnCdsSQs02SBFYmxDslN
EgOBuEwIRMsl1FEapdWCBi7srrqW3blFZsVjHORSVLbOC8Zt2oFD767jolr5c59tDSjTtbNW677r
V7LAGhU2JeZdUxo7xMrf7uWJPABvcqkOr62u/ZFv2LfC+r/CdXOUn0juhXwDoa0xHBm97R4U2uVO
degzF7L68ErfQz/n5V16elL8nTcgvgOPcEB2mz1rVAVqNBvQ+iRVZX2tvUODP+HphAZXv/0FwIaM
0vwBAAA=#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.3.130
     Generated on:       2016-12-11 15:34
     Generated by:       ibelmans
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2016
#>


#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
ZAMAAB+LCAAAAAAABAC9k99Lw0AMx98F/4djz+Xa2tU6uBZkshdBxYn6mnbpOLwfI7lz9L93mzJF
HwSRkpd8E5IPIYm6x86/Ig1XEEDsHNbe1ZMzmU+a0xMh1C3ptXZgFtrgDVhslgEoxI3cMKv0R/ZQ
c8mMtjUa+aA/I0NjufNkdJuIxw/WVGZ7S8Q8mhAJa4cxEJhE3MVdj+4ahwf/gq5uqwrKrjzPZ8UU
s4uZSo9dv1OWAwe0YzDkk3Yrv2W58GR5FOJ+U+OACLbarf/Cyoq+7Ks+z1dlBgX8znq2ZpSZ5p7w
/0FH+X7yKv36Vc0baArZVmQDAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

####################################################################################################
### Begin: Script information ######################################################################
####################################################################################################

<#
.SYNOPSIS
    PowerShell GUI script to reset an Active Directory user's password. 
.DESCRIPTION
    PowerShell GUI script to reset an Active Directory user's password.
.NOTES
    Author   : Ingvald Belmans
    Website  : http://www.supersysadmin.com
    Version  : 2.0 
    Changelog:
        - 1.0 (2016-01-04) Initial version.
		- 1.1 (2016-01-05) Cleanup output text and simplify try/catch for $ButtonMainChangePasswordChangePassword_Click.
		- 1.2 (2016-12-08) Fixed bug where error handling was not working when using implicit remoting for the ActiveDirectory PowerShell module.
		- 2.0 (2016-12-11)
			- Added support for alternate credentials.
			- Added options for "User cannot change password" and "Password never expires".
			- Added support to connect to other domains/forests.
			- Removed unnecessary logging of ActiveDirectory PowerShell module being loaded at each password update.
			- Generalized application name, version and URL.
			- Some code correction (parameters not fully written out).
			- Code commenting restructuring.
.LINK
    http://www.supersysadmin.com
#>

####################################################################################################
### End: Script information ########################################################################
####################################################################################################

####################################################################################################
### Begin: Main function ###########################################################################
####################################################################################################

#region function Main
function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>	
	Param
	(
		[String]$Commandline
	)	
	if((Show-MainForm_psf) -eq 'OK')
	{		
	}	
	$global:ExitCode = 0 #Set the exit code for the Packager
}
#endregion

####################################################################################################
### End: Main function #############################################################################
####################################################################################################

#endregion Source: Startup.pss

#region Source: MainForm.psf
function Show-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
9jkAAB+LCAAAAAAABADlW1tv4jgUfl9p/4PF06yEgHApVKJIlLar0badqnRn960ywYC3SYwcZyj7
6/c4JjSQhNjcprCq1DbF5/7587Hjtp+JzX4QPr/BAiP4xafMuypUS1ah8+svCLW/cTqmHnbuqEMe
sUs6D5h6d4y7pak/apcTHyuhwT/EFkjMp+Sq0J/7grilv6g3ZDO/JGXV9yJK+6iIvi+8qJcq8quI
eoEjAk6uPBIIjp0iegoGDrX/IPMX9ka8q0GziRt248K6rNVJpXVZQB64clWQ+qS7BWRPqDPkMLTQ
Y57gzPFVeODrE2dTwsV8IdMNBOvb2CE31CWe9AOGXhSRVWuXo6F5og9sSAqdO7CUK9NzKPFEn/4L
Ao3WZRHVK/mGZEwPxAv6gtNpFAgMeyYjAkHaJBoXjVFJKEfqcvVTj7qBq7y6qDTAq3o1V0qWX0at
cp47vC8wF0/MpwJyXOj0IA2E921OSL7sC3kXhU735k+f8GfiE/GEfX/G+DApefsDFC/E7hkefnj4
Kh/b5XBA2uj+hM282PDweW18PtB/5yyYXrP3g4M9MiR9/RaIaSA2wT4FvZ49YbzQeWHTIrpmQjCY
oPdkJIromY4nSSgnVdwzG6tqWjWYMS1LQ0ahJum8huhi1lyArWrlUkPgBQ++ekPyDkJ6o/uCwfy6
w45PdARCVGa7nw+WZ2pPpJZj4CVmSxcyewFNUokkSiAAYFrmYAixVao2pnqiH4hrShBoySjEpYav
JQ8cxRznGnM/JAebDKEmggLx64kr1NZbMEOaaajdhFu9CBUQY5+nCsW5Tkr0Jtgbk2FGal5jQ1ZJ
UOpX0F6uL6uPn5QkVTDRymFGlh+4q1XBnWprK6Zb9UCb8aoN2Y/Um0aMl+wq9sZ4Kgy0KY58CPQm
xH47BgQiQ8kCRD8fCfTBt+9TyolvSogfwIAatZJNUzYwzPwyoJpqXS6QdUOmScNLFgAiB5EnPUTE
wEXo4L5TP8BOX8wdco3ttx5zwhWFB2kIXOOtMGlkuKQusyS+rorn0NqpwFg2xT3seUyYMFwOlBtp
vZw5lLN8Ozic9WaigrN0Etmhl5CykNumJn4eDdNZ2TxfXD8E/lqsXfEIRbtnY7Zxm58LcKPmcQcn
D450vYkaQ7oL7q7jHGFAIwxBjrbPR0X9xhQfAP7XAWxtvIODX5lJhrxHIrcsk6ZEzyFjTKe1y5sw
rTkHNLvR/WMXavumm6zXcPR5bKEeyWzX/ZNVBUxW0sg3f/8UM6+9eapVrCJqap7/bGge9rR3ghCW
UEVfxIza5LftNlDHOjeKnQzE8l81JaW9HPq0iih1G5wFngzfTfirpd8rmK7JwEKqdjHiyOagbZax
n4sR66dgxPRgMMN3I4zo2zQ92tsJIyeyqsgGL6zFDkvKlidykWmD5QSCrpu9fNB5LbLlchL5j770
sdu1bRZ4Qj6fzpqiV/zPxxUbkHN4nth5ni/fFB+81GvvpE1m+FfwaxUD8i8b8cuYo4yBVTn4cOHF
3Ep5E59wJLxFQR3y8VZeFU5+dj4R9jgZwi6HAoedd6A3zF25YpESo9H7c3Bbf0u0MqX035vL2yap
p0uG3JO6ELngky99Si52K+y0+qCxIh0PBrlTN+Nyyg083rCZt0ZXnxTh+lTVHTB5QaAcQ/QqwE89
wHs2Pufwbt9pdvk0b3dlKs+/7qXa5fSOJ51DUvSeMF1IdG2XW5DUTK9VkfnNv6qn8puqN+Vcc5Nj
ydPMEy6RYrjtihTKHqRMGZpNChWqOKtShWS2XaWkqG6hGlWDQqUrNqmT1HA2ZYo3//+jVikW9q28
0pyxBzqn7iIWYs8hWCvkXRqOmH7NidxsGfQd2epPfyYmILlT9te16dJqeGVbm1alEbTRii7HbnD9
HGk3MRkz8nzr4YEjL12kHzZvh4114wfBRmhk79hYd/1ssLE4pjKvqxLULOGFZUC2WZp1y6bk8yrU
9X3iQt6IH+lf/GXecX2bcYcO9pD7dnmpdd2KqvYxbOwdUfkW5f8OHscQxzPqjbexVamNGqPmyLKG
jQqu4Xxbf7vOUWLqMU72b2j5qCDfLsf/z7PzH/Th6PP2OQAA#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$FormMain = New-Object 'System.Windows.Forms.Form'
	$GroupBoxMainOutput = New-Object 'System.Windows.Forms.GroupBox'
	$RichTextBoxMainOutput = New-Object 'System.Windows.Forms.RichTextBox'
	$GroupBoxMainChangePassword = New-Object 'System.Windows.Forms.GroupBox'
	$CheckBoxMainChangePasswordPasswordNeverExpires = New-Object 'System.Windows.Forms.CheckBox'
	$CheckBoxMainChangePasswordUserCannotChangePassword = New-Object 'System.Windows.Forms.CheckBox'
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon = New-Object 'System.Windows.Forms.CheckBox'
	$ButtonMainChangePasswordChangePassword = New-Object 'System.Windows.Forms.Button'
	$GroupBoxMainNewPassword = New-Object 'System.Windows.Forms.GroupBox'
	$TextBoxMainNewPassword2 = New-Object 'System.Windows.Forms.TextBox'
	$TextBoxMainNewPassword1 = New-Object 'System.Windows.Forms.TextBox'
	$GroupBoxMainUserName = New-Object 'System.Windows.Forms.GroupBox'
	$TextBoxMainUserName = New-Object 'System.Windows.Forms.TextBox'
	$MenuStripMain = New-Object 'System.Windows.Forms.MenuStrip'
	$ToolStripMenuItemMainFile = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$ToolStripMenuItemMainFileLog = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$ToolStripMenuItemMainFileAbout = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$ToolStripMenuItemMainFileExit = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$ToolStripMenuItemMainCredentials = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$ToolStripMenuItemMainCredentialsEnterCredentials = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$ToolStripMenuItemMainCredentialsClearCredentials = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$ToolStripMenuItemMainDomain = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	#region Form > Main
	####################################################################################################
	### Begin: Form > Main #############################################################################
	####################################################################################################
	
	# Form load.
	$FormMain_Load =
	{
		# Application name and version.
		$global:SSAApplicationName = "ADUserResetPassword"
		$global:SSAApplicationVersion = "2.0"
		$global:SSAApplicationURL = "http://supersysadmin.com/96/powershell-gui-script-to-reset-an-active-directory-users-password/"
		
		# Set application title.
		$global:SSAApplicationDisplayCurrentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent()
		$FormMain.Text = "$SSAApplicationName v$SSAApplicationVersion ($($SSAApplicationDisplayCurrentUser.Name))"
		
		# Create log file.
		$SSALogFileTimeStamp = Get-Date -UFormat "%Y%m%d_%H%M%S"
		$global:SSALogFile = New-Item -ItemType File -Path "$env:USERPROFILE\Documents" -Name "SSA_ADUserResetPassword_$SSALogFileTimeStamp.log"
		
		# Define variable for application user.
		$global:SSAApplicationUser = @{ }
		
		# Populate ActiveDirectoryDomain variable with the current domain.
		$global:SSAActiveDirectoryDomain = (Get-WmiObject -Class Win32_ComputerSystem).Domain
		
		# Set global ErrorActionPreference to Stop to ensure that error handling correctly works when using implicit remoting for the ActiveDirectory PowerShell module.
		$global:ErrorActionPreference = "Stop"
		
		# Show result of log file creation.
		Add-SSAOutput -OutputText "Creating log file."
		if (Test-Path -Path $SSALogFile)
		{
			Add-SSAOutput -OutputText "Logfile $SSALogFile has been created."
		}
		else
		{
			Add-SSAOutput -OutputText "Logfile $SSALogFile could not be created."
		}
	}
	
	# Form Shown.
	$FormMain_Shown =
	{
		Import-SSAActiveDirectoryModule
		if ($SSAActiveDirectoryModuleLoaded -eq $False)
		{
			[System.Windows.Forms.MessageBox]::Show("The ActiveDirectory PowerShell module could not be loaded. You can review the log for more details. Please restart the application to try again.", "Error", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error)
		}	
	}
	
	# Menu File > About.
	$ToolStripMenuItemMainFileAbout_Click =
	{
		Start-Process -FilePath $SSAApplicationURL
	}
	
	# Menu File > Log.
	$ToolStripMenuItemMainFileLog_Click =
	{
		Invoke-Item -Path $SSALogFile
	}
	
	# Menu File > Exit.
	$ToolStripMenuItemMainFileExit_Click =
	{
		$FormMain.Close()
	}
	
	# Menu Credentials > Enter Credentials.
	$ToolStripMenuItemMainCredentialsEnterCredentials_Click =
	{
		Add-SSAOutput -OutputText "Entering alternate credentials."
		try
		{
			$global:SSAApplicationUser = @{ Credential = Get-Credential -Message "Enter Credentials" -ErrorAction Stop }
			$FormMain.Text = "$SSAApplicationName v$SSAApplicationVersion ($($SSAApplicationUser.Credential.UserName))"
			$ToolStripMenuItemMainCredentialsEnterCredentials.Enabled = $False
			$ToolStripMenuItemMainCredentialsClearCredentials.Enabled = $True
			Add-SSAOutput -OutputText "Alternate credentials have been saved. The current user is now $($SSAApplicationUser.Credential.UserName)."
		}
		catch
		{
			Add-SSAOutput -OutputText $_
			Add-SSAOutput -OutputText "Alternate credentials could not be saved."
		}
	}
	
	# Menu Credentials > Clear Credentials.
	$ToolStripMenuItemMainCredentialsClearCredentials_Click =
	{
		Add-SSAOutput -OutputText "Clearing alternate credentials."
		$global:SSAApplicationUser = @{ }
		$global:SSAApplicationDisplayCurrentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent()
		$FormMain.Text = "$SSAApplicationName v$SSAApplicationVersion ($($SSAApplicationDisplayCurrentUser.Name))"
		$ToolStripMenuItemMainCredentialsClearCredentials.Enabled = $False
		$ToolStripMenuItemMainCredentialsEnterCredentials.Enabled = $True
		Add-SSAOutput -OutputText "Alternate credentials have been cleared. The current user is now $($SSAApplicationDisplayCurrentUser.Name)."
	}
	
	# Menu Domain.
	$ToolStripMenuItemMainDomain_Click =
	{
		Add-SSAOutput -OutputText "Updating Active Directory Domain."
		[Reflection.Assembly]::LoadWithPartialName("Microsoft.VisualBasic")
		$SSAUpdateActiveDirectoryDomain = [Microsoft.VisualBasic.Interaction]::InputBox("Enter in the textbox below the Active Directory Domain against which you want to run your queries:", "Active Directory Domain", $SSAActiveDirectoryDomain)
		# If you press Cancel or press OK when the textbox is empty, an empty string is returned (not the same as $null).
		if ($SSAUpdateActiveDirectoryDomain -eq "")
		{
			if ($SSAActiveDirectoryDomain -eq $null)
			{
				$global:SSAActiveDirectoryDomain = (Get-WmiObject -Class Win32_ComputerSystem).Domain
				Add-SSAOutput -OutputText "Input was empty or cancelled and current domain is null. Resetting domain to $SSAActiveDirectoryDomain."
			}
			else
			{
				Add-SSAOutput -OutputText "Input was empty or cancelled and current domain is not null. No action was taken."
			}		
		}
		else
		{
			if ($SSAUpdateActiveDirectoryDomain -eq $SSAActiveDirectoryDomain)
			{
				Add-SSAOutput -OutputText "Input was equal to current domain. No action was taken."
			}
			else
			{
				$global:SSAActiveDirectoryDomain = $SSAUpdateActiveDirectoryDomain
				Add-SSAOutput -OutputText "Active Directory Domain has been updated to '$SSAActiveDirectoryDomain'."
			}		
		}	
	}
	
	# When checkbox CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon is checked, unsure checkboxs CheckBoxMainChangePasswordUserCannotChangePassword and CheckBoxMainChangePasswordPasswordNeverExpires are unchecked.
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon_CheckedChanged =
	{
		if ($CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Checked -eq $True)
		{
			$CheckBoxMainChangePasswordUserCannotChangePassword.Checked = $False
			$CheckBoxMainChangePasswordPasswordNeverExpires.Checked = $False
		}	
	}
	
	# When checkbox CheckBoxMainChangePasswordUserCannotChangePassword is checked, unsure checkbox CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon is unchecked.
	$CheckBoxMainChangePasswordUserCannotChangePassword_CheckedChanged =
	{
		if ($CheckBoxMainChangePasswordUserCannotChangePassword.Checked -eq $True)
		{
			$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Checked = $False
		}
	}
	
	# When checkbox CheckBoxMainChangePasswordPasswordNeverExpires is checked, unsure checkbox CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon is unchecked.
	$CheckBoxMainChangePasswordPasswordNeverExpires_CheckedChanged =
	{
		if ($CheckBoxMainChangePasswordPasswordNeverExpires.Checked -eq $True)
		{
			$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Checked = $False
		}	
	}
	
	# Change password.
	$ButtonMainChangePasswordChangePassword_Click =
	{
		if ($SSAActiveDirectoryModuleLoaded -eq $True)
		{
			Get-SSAUserName
			if ($SSAUserName)
			{
				Add-SSAOutput -OutputText "Changing password of user '$SSAUserName'."
				try
				{
					$QueryADUser = Get-ADUser -Identity $SSAUserName -Properties * @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop
					Get-SSAPassword1
					Get-SSAPassword2
					if ($SSAPassword1 -and $SSAPassword2)
					{
						if ($SSAPassword1 -eq $SSAPassword2)
						{
							Set-ADAccountPassword -Identity $SSAUserName -NewPassword (ConvertTo-SecureString -String $SSAPassword1 -AsPlainText –Force) –Reset @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop -PassThru
							Add-SSAOutput -OutputText "Password for user '$SSAUserName' has been updated."
							if ($CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Checked -eq $True)
							{
								if ($QueryADUser.pwdLastSet -ne 0)
								{
									if ($QueryADUser.PasswordNeverExpires -eq $True)
									{
										Set-ADUser -Identity $SSAUserName -PasswordNeverExpires $False @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop									
									}
									Set-ADUser -Identity $SSAUserName -ChangePasswordAtLogon $True @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop
									Add-SSAOutput -OutputText "Option 'Change password at next logon' has been enabled for user '$SSAUserName'."
								}
							}
							else
							{
								if ($QueryADUser.pwdLastSet -eq 0)
								{
									Set-ADUser -Identity $SSAUserName -ChangePasswordAtLogon $False @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop
									Add-SSAOutput -OutputText "Option 'Change password at next logon' has been disabled for user '$SSAUserName'."
								}
							}
							if ($CheckBoxMainChangePasswordUserCannotChangePassword.Checked -eq $True)
							{
								if ($QueryADUser.CannotChangePassword -ne $True)
								{
									Set-ADUser -Identity $SSAUserName -CannotChangePassword $True @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop
									Add-SSAOutput -OutputText "Option 'User cannot change password' has been enabled for user '$SSAUserName'."
								}
							}
							else
							{
								if ($QueryADUser.CannotChangePassword -ne $False)
								{
									Set-ADUser -Identity $SSAUserName -CannotChangePassword $False @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop
									Add-SSAOutput -OutputText "Option 'User cannot change password' has been disabled for user '$SSAUserName'."
								}
							}
							if ($CheckBoxMainChangePasswordPasswordNeverExpires.Checked -eq $True)
							{
								if ($QueryADUser.PasswordNeverExpires -ne $True)
								{
									Set-ADUser -Identity $SSAUserName -PasswordNeverExpires $True @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop
									Add-SSAOutput -OutputText "Option 'Password never expires' has been enabled for user '$SSAUserName'."
								}
							}
							else
							{
								if ($QueryADUser.PasswordNeverExpires -ne $False)
								{
									Set-ADUser -Identity $SSAUserName -PasswordNeverExpires $False @SSAApplicationUser -Server $SSAActiveDirectoryDomain -ErrorAction Stop
									Add-SSAOutput -OutputText "Option 'Password never expires' has been disabled for user '$SSAUserName'."
								}
							}						
						}
						else
						{
							Add-SSAOutput -OutputText "Passwords do not match, please review your input."
						}
					}
					else
					{
						Add-SSAOutput -OutputText "One or both password fields are empty, please review your input."
					}
				}
				catch
				{
					Add-SSAOutput -OutputText "$_"
				}
			}
			else
			{
				Add-SSAOutput -OutputText "UserName field is empty, please review your input."
			}
		}
		else
		{
			Add-SSAOutput -OutputText "ActiveDirectory PowerShell module is currently not loaded, cannot proceed with the request. Restart the application to attempt load the module."
		}
	}
	
	# Scroll Output window to bottom.
	$RichTextBoxMainOutput_TextChanged =
	{
		$RichTextBoxMainOutput.SelectionStart = $RichTextBoxMainOutput.Text.Length
		$RichTextBoxMainOutput.ScrollToCaret()
	}
	
	####################################################################################################
	### End: Form > Main ###############################################################################
	####################################################################################################
	#endregion
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$FormMain.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_RichTextBoxMainOutput = $RichTextBoxMainOutput.Text
		$script:MainForm_CheckBoxMainChangePasswordPasswordNeverExpires = $CheckBoxMainChangePasswordPasswordNeverExpires.Checked
		$script:MainForm_CheckBoxMainChangePasswordUserCannotChangePassword = $CheckBoxMainChangePasswordUserCannotChangePassword.Checked
		$script:MainForm_CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon = $CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Checked
		$script:MainForm_TextBoxMainNewPassword2 = $TextBoxMainNewPassword2.Text
		$script:MainForm_TextBoxMainNewPassword1 = $TextBoxMainNewPassword1.Text
		$script:MainForm_TextBoxMainUserName = $TextBoxMainUserName.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$RichTextBoxMainOutput.remove_TextChanged($RichTextBoxMainOutput_TextChanged)
			$CheckBoxMainChangePasswordPasswordNeverExpires.remove_CheckedChanged($CheckBoxMainChangePasswordPasswordNeverExpires_CheckedChanged)
			$CheckBoxMainChangePasswordUserCannotChangePassword.remove_CheckedChanged($CheckBoxMainChangePasswordUserCannotChangePassword_CheckedChanged)
			$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.remove_CheckedChanged($CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon_CheckedChanged)
			$ButtonMainChangePasswordChangePassword.remove_Click($ButtonMainChangePasswordChangePassword_Click)
			$FormMain.remove_Load($FormMain_Load)
			$FormMain.remove_Shown($FormMain_Shown)
			$ToolStripMenuItemMainFileLog.remove_Click($ToolStripMenuItemMainFileLog_Click)
			$ToolStripMenuItemMainFileAbout.remove_Click($ToolStripMenuItemMainFileAbout_Click)
			$ToolStripMenuItemMainFileExit.remove_Click($ToolStripMenuItemMainFileExit_Click)
			$ToolStripMenuItemMainCredentialsEnterCredentials.remove_Click($ToolStripMenuItemMainCredentialsEnterCredentials_Click)
			$ToolStripMenuItemMainCredentialsClearCredentials.remove_Click($ToolStripMenuItemMainCredentialsClearCredentials_Click)
			$ToolStripMenuItemMainDomain.remove_Click($ToolStripMenuItemMainDomain_Click)
			$FormMain.remove_Load($Form_StateCorrection_Load)
			$FormMain.remove_Closing($Form_StoreValues_Closing)
			$FormMain.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$FormMain.SuspendLayout()
	$GroupBoxMainOutput.SuspendLayout()
	$GroupBoxMainChangePassword.SuspendLayout()
	$GroupBoxMainNewPassword.SuspendLayout()
	$GroupBoxMainUserName.SuspendLayout()
	$MenuStripMain.SuspendLayout()
	#
	# FormMain
	#
	$FormMain.Controls.Add($GroupBoxMainOutput)
	$FormMain.Controls.Add($GroupBoxMainChangePassword)
	$FormMain.Controls.Add($GroupBoxMainNewPassword)
	$FormMain.Controls.Add($GroupBoxMainUserName)
	$FormMain.Controls.Add($MenuStripMain)
	$FormMain.AutoScaleDimensions = '6, 13'
	$FormMain.AutoScaleMode = 'Font'
	$FormMain.ClientSize = '589, 403'
	$FormMain.MainMenuStrip = $MenuStripMain
	$FormMain.MinimumSize = '605, 442'
	$FormMain.Name = 'FormMain'
	$FormMain.StartPosition = 'CenterScreen'
	$FormMain.Text = 'ADUserResetPassword'
	$FormMain.add_Load($FormMain_Load)
	$FormMain.add_Shown($FormMain_Shown)
	#
	# GroupBoxMainOutput
	#
	$GroupBoxMainOutput.Controls.Add($RichTextBoxMainOutput)
	$GroupBoxMainOutput.Anchor = 'Top, Bottom, Left, Right'
	$GroupBoxMainOutput.Location = '13, 181'
	$GroupBoxMainOutput.Name = 'GroupBoxMainOutput'
	$GroupBoxMainOutput.Size = '563, 209'
	$GroupBoxMainOutput.TabIndex = 5
	$GroupBoxMainOutput.TabStop = $False
	$GroupBoxMainOutput.Text = 'Output'
	#
	# RichTextBoxMainOutput
	#
	$RichTextBoxMainOutput.Anchor = 'Top, Bottom, Left, Right'
	$RichTextBoxMainOutput.Font = 'Consolas, 8.25pt'
	$RichTextBoxMainOutput.Location = '7, 20'
	$RichTextBoxMainOutput.Name = 'RichTextBoxMainOutput'
	$RichTextBoxMainOutput.ScrollBars = 'ForcedVertical'
	$RichTextBoxMainOutput.Size = '548, 179'
	$RichTextBoxMainOutput.TabIndex = 0
	$RichTextBoxMainOutput.Text = ''
	$RichTextBoxMainOutput.add_TextChanged($RichTextBoxMainOutput_TextChanged)
	#
	# GroupBoxMainChangePassword
	#
	$GroupBoxMainChangePassword.Controls.Add($CheckBoxMainChangePasswordPasswordNeverExpires)
	$GroupBoxMainChangePassword.Controls.Add($CheckBoxMainChangePasswordUserCannotChangePassword)
	$GroupBoxMainChangePassword.Controls.Add($CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon)
	$GroupBoxMainChangePassword.Controls.Add($ButtonMainChangePasswordChangePassword)
	$GroupBoxMainChangePassword.Location = '320, 28'
	$GroupBoxMainChangePassword.Name = 'GroupBoxMainChangePassword'
	$GroupBoxMainChangePassword.Size = '256, 147'
	$GroupBoxMainChangePassword.TabIndex = 3
	$GroupBoxMainChangePassword.TabStop = $False
	$GroupBoxMainChangePassword.Text = 'Change Password'
	#
	# CheckBoxMainChangePasswordPasswordNeverExpires
	#
	$CheckBoxMainChangePasswordPasswordNeverExpires.Location = '6, 82'
	$CheckBoxMainChangePasswordPasswordNeverExpires.Name = 'CheckBoxMainChangePasswordPasswordNeverExpires'
	$CheckBoxMainChangePasswordPasswordNeverExpires.Size = '243, 24'
	$CheckBoxMainChangePasswordPasswordNeverExpires.TabIndex = 3
	$CheckBoxMainChangePasswordPasswordNeverExpires.Text = 'Password never expires'
	$CheckBoxMainChangePasswordPasswordNeverExpires.UseVisualStyleBackColor = $True
	$CheckBoxMainChangePasswordPasswordNeverExpires.add_CheckedChanged($CheckBoxMainChangePasswordPasswordNeverExpires_CheckedChanged)
	#
	# CheckBoxMainChangePasswordUserCannotChangePassword
	#
	$CheckBoxMainChangePasswordUserCannotChangePassword.Location = '6, 51'
	$CheckBoxMainChangePasswordUserCannotChangePassword.Name = 'CheckBoxMainChangePasswordUserCannotChangePassword'
	$CheckBoxMainChangePasswordUserCannotChangePassword.Size = '243, 24'
	$CheckBoxMainChangePasswordUserCannotChangePassword.TabIndex = 2
	$CheckBoxMainChangePasswordUserCannotChangePassword.Text = 'User cannot change password'
	$CheckBoxMainChangePasswordUserCannotChangePassword.UseVisualStyleBackColor = $True
	$CheckBoxMainChangePasswordUserCannotChangePassword.add_CheckedChanged($CheckBoxMainChangePasswordUserCannotChangePassword_CheckedChanged)
	#
	# CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon
	#
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Location = '6, 20'
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Name = 'CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon'
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Size = '243, 24'
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.TabIndex = 1
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.Text = 'User must change password at next logon'
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.UseVisualStyleBackColor = $True
	$CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon.add_CheckedChanged($CheckBoxMainChangePasswordUserMustChangePasswordAtNextLogon_CheckedChanged)
	#
	# ButtonMainChangePasswordChangePassword
	#
	$ButtonMainChangePasswordChangePassword.Location = '6, 112'
	$ButtonMainChangePasswordChangePassword.Name = 'ButtonMainChangePasswordChangePassword'
	$ButtonMainChangePasswordChangePassword.Size = '243, 28'
	$ButtonMainChangePasswordChangePassword.TabIndex = 4
	$ButtonMainChangePasswordChangePassword.Text = 'Change Password'
	$ButtonMainChangePasswordChangePassword.UseVisualStyleBackColor = $True
	$ButtonMainChangePasswordChangePassword.add_Click($ButtonMainChangePasswordChangePassword_Click)
	#
	# GroupBoxMainNewPassword
	#
	$GroupBoxMainNewPassword.Controls.Add($TextBoxMainNewPassword2)
	$GroupBoxMainNewPassword.Controls.Add($TextBoxMainNewPassword1)
	$GroupBoxMainNewPassword.Location = '12, 100'
	$GroupBoxMainNewPassword.Name = 'GroupBoxMainNewPassword'
	$GroupBoxMainNewPassword.Size = '301, 75'
	$GroupBoxMainNewPassword.TabIndex = 2
	$GroupBoxMainNewPassword.TabStop = $False
	$GroupBoxMainNewPassword.Text = 'New Password (twice)'
	#
	# TextBoxMainNewPassword2
	#
	$TextBoxMainNewPassword2.Font = 'Consolas, 8.25pt'
	$TextBoxMainNewPassword2.Location = '8, 47'
	$TextBoxMainNewPassword2.Name = 'TextBoxMainNewPassword2'
	$TextBoxMainNewPassword2.Size = '286, 20'
	$TextBoxMainNewPassword2.TabIndex = 1
	$TextBoxMainNewPassword2.UseSystemPasswordChar = $True
	#
	# TextBoxMainNewPassword1
	#
	$TextBoxMainNewPassword1.Font = 'Consolas, 8.25pt'
	$TextBoxMainNewPassword1.Location = '7, 20'
	$TextBoxMainNewPassword1.Name = 'TextBoxMainNewPassword1'
	$TextBoxMainNewPassword1.Size = '287, 20'
	$TextBoxMainNewPassword1.TabIndex = 0
	$TextBoxMainNewPassword1.UseSystemPasswordChar = $True
	#
	# GroupBoxMainUserName
	#
	$GroupBoxMainUserName.Controls.Add($TextBoxMainUserName)
	$GroupBoxMainUserName.Location = '12, 28'
	$GroupBoxMainUserName.Name = 'GroupBoxMainUserName'
	$GroupBoxMainUserName.Size = '300, 49'
	$GroupBoxMainUserName.TabIndex = 1
	$GroupBoxMainUserName.TabStop = $False
	$GroupBoxMainUserName.Text = 'UserName (SamAccountName)'
	#
	# TextBoxMainUserName
	#
	$TextBoxMainUserName.Font = 'Consolas, 8.25pt'
	$TextBoxMainUserName.Location = '7, 20'
	$TextBoxMainUserName.Name = 'TextBoxMainUserName'
	$TextBoxMainUserName.Size = '287, 20'
	$TextBoxMainUserName.TabIndex = 0
	#
	# MenuStripMain
	#
	[void]$MenuStripMain.Items.Add($ToolStripMenuItemMainFile)
	[void]$MenuStripMain.Items.Add($ToolStripMenuItemMainCredentials)
	[void]$MenuStripMain.Items.Add($ToolStripMenuItemMainDomain)
	$MenuStripMain.Location = '0, 0'
	$MenuStripMain.Name = 'MenuStripMain'
	$MenuStripMain.Size = '589, 24'
	$MenuStripMain.TabIndex = 0
	$MenuStripMain.Text = 'menustrip1'
	#
	# ToolStripMenuItemMainFile
	#
	[void]$ToolStripMenuItemMainFile.DropDownItems.Add($ToolStripMenuItemMainFileAbout)
	[void]$ToolStripMenuItemMainFile.DropDownItems.Add($ToolStripMenuItemMainFileLog)
	[void]$ToolStripMenuItemMainFile.DropDownItems.Add($ToolStripMenuItemMainFileExit)
	$ToolStripMenuItemMainFile.Name = 'ToolStripMenuItemMainFile'
	$ToolStripMenuItemMainFile.Size = '37, 20'
	$ToolStripMenuItemMainFile.Text = 'File'
	#
	# ToolStripMenuItemMainFileLog
	#
	$ToolStripMenuItemMainFileLog.Name = 'ToolStripMenuItemMainFileLog'
	$ToolStripMenuItemMainFileLog.Size = '107, 22'
	$ToolStripMenuItemMainFileLog.Text = 'Log'
	$ToolStripMenuItemMainFileLog.add_Click($ToolStripMenuItemMainFileLog_Click)
	#
	# ToolStripMenuItemMainFileAbout
	#
	$ToolStripMenuItemMainFileAbout.Name = 'ToolStripMenuItemMainFileAbout'
	$ToolStripMenuItemMainFileAbout.Size = '107, 22'
	$ToolStripMenuItemMainFileAbout.Text = 'About'
	$ToolStripMenuItemMainFileAbout.add_Click($ToolStripMenuItemMainFileAbout_Click)
	#
	# ToolStripMenuItemMainFileExit
	#
	$ToolStripMenuItemMainFileExit.Name = 'ToolStripMenuItemMainFileExit'
	$ToolStripMenuItemMainFileExit.Size = '152, 22'
	$ToolStripMenuItemMainFileExit.Text = 'Exit'
	$ToolStripMenuItemMainFileExit.add_Click($ToolStripMenuItemMainFileExit_Click)
	#
	# ToolStripMenuItemMainCredentials
	#
	[void]$ToolStripMenuItemMainCredentials.DropDownItems.Add($ToolStripMenuItemMainCredentialsEnterCredentials)
	[void]$ToolStripMenuItemMainCredentials.DropDownItems.Add($ToolStripMenuItemMainCredentialsClearCredentials)
	$ToolStripMenuItemMainCredentials.Name = 'ToolStripMenuItemMainCredentials'
	$ToolStripMenuItemMainCredentials.Size = '78, 20'
	$ToolStripMenuItemMainCredentials.Text = 'Credentials'
	#
	# ToolStripMenuItemMainCredentialsEnterCredentials
	#
	$ToolStripMenuItemMainCredentialsEnterCredentials.Name = 'ToolStripMenuItemMainCredentialsEnterCredentials'
	$ToolStripMenuItemMainCredentialsEnterCredentials.Size = '163, 22'
	$ToolStripMenuItemMainCredentialsEnterCredentials.Text = 'Enter Credentials'
	$ToolStripMenuItemMainCredentialsEnterCredentials.add_Click($ToolStripMenuItemMainCredentialsEnterCredentials_Click)
	#
	# ToolStripMenuItemMainCredentialsClearCredentials
	#
	$ToolStripMenuItemMainCredentialsClearCredentials.Enabled = $False
	$ToolStripMenuItemMainCredentialsClearCredentials.Name = 'ToolStripMenuItemMainCredentialsClearCredentials'
	$ToolStripMenuItemMainCredentialsClearCredentials.Size = '163, 22'
	$ToolStripMenuItemMainCredentialsClearCredentials.Text = 'Clear Credentials'
	$ToolStripMenuItemMainCredentialsClearCredentials.add_Click($ToolStripMenuItemMainCredentialsClearCredentials_Click)
	#
	# ToolStripMenuItemMainDomain
	#
	$ToolStripMenuItemMainDomain.Name = 'ToolStripMenuItemMainDomain'
	$ToolStripMenuItemMainDomain.Size = '61, 20'
	$ToolStripMenuItemMainDomain.Text = 'Domain'
	$ToolStripMenuItemMainDomain.add_Click($ToolStripMenuItemMainDomain_Click)
	$MenuStripMain.ResumeLayout()
	$GroupBoxMainUserName.ResumeLayout()
	$GroupBoxMainNewPassword.ResumeLayout()
	$GroupBoxMainChangePassword.ResumeLayout()
	$GroupBoxMainOutput.ResumeLayout()
	$FormMain.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $FormMain.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$FormMain.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$FormMain.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$FormMain.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $FormMain.ShowDialog()

}
#endregion Source: MainForm.psf

#region Source: Globals.ps1
	####################################################################################################
	### Begin: Custom functions ########################################################################
	####################################################################################################
	
	#region function Add-SSAOutput
	function Add-SSAOutput
	{
		[CmdletBinding()]
		Param
		(
			[Parameter(
				Mandatory = $true
				 )
			]
			$OutputText
		)
		Begin
		{
		}
		Process
		{
			$OutputDate = Get-Date -UFormat "%Y-%m-%d"
			$OutputTime = Get-Date -UFormat "%H:%M:%S"
			$RichTextBoxMainOutput.Text += "[$OutputDate][$OutputTime] $OutputText`n"
			Add-Content -Path $SSALogFile -Value "[$OutputDate][$OutputTime] $OutputText`n"
		}
		End
		{
		}
	}
	#endregion
	
	#region function Import-SSAActiveDirectoryModule
	function Import-SSAActiveDirectoryModule
	{
		[CmdletBinding()]
		Param
		(
		)
		Begin
		{
		}
		Process
		{
			Add-SSAOutput -OutputText "Loading ActiveDirectory PowerShell module."
			if ((Get-Module -name "ActiveDirectory") -eq $null)
			{
				Add-SSAOutput -OutputText "ActiveDirectory PowerShell module is currently not loaded."
				if (Get-Module -ListAvailable | Where-Object { $_.name -eq "ActiveDirectory" })
				{
					Add-SSAOutput -OutputText "ActiveDirectory PowerShell module is available, importing module."
					Import-Module -Name "ActiveDirectory"
					if ((Get-Module -name "ActiveDirectory") -eq $null)
					{
						Add-SSAOutput -OutputText "ActiveDirectory PowerShell module could not be loaded."
						$global:SSAActiveDirectoryModuleLoaded = $false
					}
					else
					{
						Add-SSAOutput -OutputText "ActiveDirectory PowerShell module has been loaded."
						$global:SSAActiveDirectoryModuleLoaded = $true
					}
				}
				else
				{
					Add-SSAOutput -OutputText "ActiveDirectory PowerShell module is not available on this computer, attempting to import it from a Domain Controller."
					try
					{
						$DomainDNSName = (Get-WmiObject -Class WIN32_ComputerSystem -ErrorAction Stop).Domain
						$DomainNetBiosName = (Get-WmiObject -Class Win32_NTDomain -Filter "DnsForestName = '$((Get-WmiObject Win32_ComputerSystem).Domain)'" -ErrorAction Stop).DomainName
						$DomainControllerName = ((Get-WmiObject -Class WIN32_NTDomain -Filter "DomainName = '$DomainNetBiosName'" -ErrorAction Stop).DomainControllerName) -replace "\\", ""
						$DomainController = "$DomainControllerName.$DomainDNSName"
						$DomainControllerSession = New-PSSession -Computername $DomainController -ErrorAction Stop
						Invoke-Command -Command { Import-Module -Name "ActiveDirectory" } -Session $DomainControllerSession -ErrorAction Stop
						$ImportSession = Import-PSSession -Session $DomainControllerSession -Module ActiveDirectory -AllowClobber -ErrorAction Stop
						if ($ImportSession.Name)
						{
							Add-SSAOutput -OutputText "ActiveDirectory PowerShell module has been imported from Domain Controller $DomainController."
							$global:SSAActiveDirectoryModuleLoaded = $true
						}
					}
					catch
					{
						Add-SSAOutput -OutputText "ActiveDirectory PowerShell module could not be imported. Possible reasons are: This workstation is not joined to the Active Directory domain, PowerShell remoting towards the Domain Controller does not work or is not setup, the current user does not have appropriate rights to open a PowerShell session to the Domain Controller."
						$global:SSAActiveDirectoryModuleLoaded = $false
					}
				}
			}
			else
			{
				Add-SSAOutput -OutputText "ActiveDirectory PowerShell module is already loaded."
				$global:SSAActiveDirectoryModuleLoaded = $true
			}
		}
		End
		{
		}
	}
	#endregion
	
	#region function Get-SSAUserName
	function Get-SSAUserName
	{
		[CmdletBinding()]
		Param
		(
		)
		Begin
		{
		}
		Process
		{
			$global:SSAUserName = $TextBoxMainUserName.text
		}
		End
		{
		}
	}
	#endregion
	
	#region function Get-SSAPassword1
	function Get-SSAPassword1
	{
		[CmdletBinding()]
		Param
		(
		)
		Begin
		{
		}
		Process
		{
			$global:SSAPassword1 = $TextBoxMainNewPassword1.text
		}
		End
		{
		}
	}
	#endregion
	
	#region function Get-SSAPassword2
	function Get-SSAPassword2
	{
		[CmdletBinding()]
		Param
		(
		)
		Begin
		{
		}
		Process
		{
			$global:SSAPassword2 = $TextBoxMainNewPassword2.text
		}
		End
		{
		}
	}
	#endregion
	
	####################################################################################################
	### End: Custom functions ##########################################################################
	####################################################################################################
	
#endregion Source: Globals.ps1

#Start the application
Main ($CommandLine)
